version: '3.8'

services:
  frontend:
    build:
      context: ./SEAI-Frontend 
      dockerfile: Dockerfile
    container_name: react-app
    ports:
      - "8080:8080"
    volumes:
      - ./SEAI-Frontend:/app 
      - /app/node_modules    
    environment:
      - VITE_BACKENDURL=http://localhost:3000  
    networks:
      - app-network

  backend:
    build:
      context: ./SEAI_backend 
      dockerfile: Dockerfile
    container_name: node-app
    ports:
      - "3000:3000" 
    volumes:
      - ./SEAI_backend:/app  
      - /app/node_modules    
    environment:
      - FRONTENDURL=http://localhost:8080  
      - GEMINIAIKEY=AIzaSyDzCRW-UMRzufhMHmsHIFnb_emfKRMbKYY  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge